/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Stat
 */
export interface Stat {
    /**
     * 
     * @type {number}
     * @memberof Stat
     */
    points: number;
    /**
     * 
     * @type {number}
     * @memberof Stat
     */
    level: number;
    /**
     * 
     * @type {string}
     * @memberof Stat
     */
    readonly url?: string;
}

export function StatFromJSON(json: any): Stat {
    return StatFromJSONTyped(json, false);
}

export function StatFromJSONTyped(json: any, ignoreDiscriminator: boolean): Stat {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'points': json['points'],
        'level': json['level'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function StatToJSON(value?: Stat | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'points': value.points,
        'level': value.level,
    };
}


