version: "3"

services:
  app:
    container_name: joc-app
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:0-14-bullseye

    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      FULLY_QUALIFIED_DOMAIN: ${FULLY_QUALIFIED_DOMAIN}

    init: true
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces/

    user: node
    working_dir: /workspaces/
    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /workspaces/.devcontainer/entrypoint.sh
    command: sleep infinity
    ports:
      - 3000:3000
