name: Deploy to AWS

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      FULLY_QUALIFIED_DOMAIN: "judgeofcharacter.xyz"
      AWS_DEFAULT_REGION: "ap-southeast-2"
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: install frontend deps
        working-directory: frontend
        run: npm ci

      - name: install infra deps
        working-directory: joc-infra
        run: npm ci

      - name: deploy
        run: make deploy
